image: maven:3-jdk-8

stages:
  - build
  - test
  
variables:
  HEADLESS_TESTFX: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500 -Dprism.verbose=true"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
# before_script:
#     - apt-get update
#     - apt-get install -y openjfx

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd Runway-Redeclaration
    - mvn compile 

test:
  stage: test
  script:
    - cd Runway-Redeclaration
    - mvn -Dtest=CalculationsTest test
    - mvn -DargLine=\"$HEADLESS_TESTFX\"" verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  only:
    - master