image: maven:latest

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd Runway-Redeclaration
    - mvn compile

test:
  stage: test
  script:
    - mvn test