image: maven:3-jdk-8

stages:
  - build
  - test
  
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
before_script:
    - apt-get update
    - apt-get -y openjfx

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd Runway-Redeclaration
    - mvn compile

test:
  stage: test
  script:
    - cd Runway-Redeclaration
    - mvn -Dtest=CalculationsTest test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml